# .github/workflows/assignment1.yml
name: Assignment 1 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # allows manual triggering

jobs:
  build-and-test:
    runs-on: self-hosted   # uses your configured runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure full-test.sh is executable
        run: chmod +x full-test.sh

      - name: Run full test
        run: ./full-test.sh

