# .github/workflows/assignment1.yml
name: Assignment 1 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted  # use your configured self-hosted runner
    timeout-minutes: 10    # prevent jobs from hanging forever
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Run full test
        working-directory: assignment1   # set this if full-test.sh is in assignment1/
        run: |
          chmod +x full-test.sh
          ./full-test.sh

